version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=easyappointments
        ports:
            - ${MYSQL_PORT}:3306
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ../:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
